### ISSUE TITLE
Add support for RAK7244C / GPS over I2C

### ISSUE THREAD

**Issue by d4rkdpg** [chirpstack/chirpstack-concentratord#105]
Hi can you add support for this please

RAK7244C - this is the Cellular version that includes the RPi 4, [RAK2245]and the [RAK2013 Cellular Pi HAT rak2013-cellular-pi-hat.

I believe it is RAK7243/7244.  I cant get gps to work becuase i think this is a special version which used 12c for gps see here: https://github.com/RAKWireless/rak_common_for_gateway/tree/master/lora/rak7243

thanks

**Comment by brocaar** [comment]
I'm closing this, as this is currently not planned.
