### ISSUE TITLE
AS923-3 on my Seeed WM1302 not working

### ISSUE THREAD

**Issue by girnrajbir** [chirpstack/chirpstack-concentratord#150]
I have installed Chirpstack Gateway OS and I have been having issues when I select AS923-3 as frequency plan on my Seeed WM1302

![image](https://github.com/chirpstack/chirpstack-concentratord/assets/93965522/12e90369-2020-44d6-b541-9ee7daa5fa27)

on the footer it shows "Gateway ID: could not read gateway id" becuase of this it wont connect to network server
however changing the frequency plan to like AS923 does make the gateway id show up and connect to the network server.

the frequncy plan in my country is AS923-3.

**Comment by brocaar** [comment]
@girnrajbir I have confirmed the issue, the above commit fixes it. This will be included in the next ChirpStack Gateway OS release. Thanks for reporting :+1:
