### ISSUE TITLE
Add support of setup reComputer r1000 (based on RPi CM4) + WM1302 SPI (may be USB too) module.

### ISSUE THREAD

**Issue by BrainNull** [chirpstack/chirpstack-concentratord#180]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-concentratord) of this repository and believe that this is not a duplicate.

## Summary

The pin configuration is different from a regular RPi4. Like here:  https://wiki.seeedstudio.com/WM1302_module/#step3-get-and-compile-sx1302-source-code
## Implementation description

Need adjust the pin configuration according to the instructions: https://wiki.seeedstudio.com/recomputer_r/#lora-module

## Can you implement this by yourself and make a pull request?
No

**Comment by brocaar** [comment]
This commit makes it possible to override the pin configs of all concentrator modules: https://github.com/chirpstack/chirpstack-concentratord/commit/0af7d7cf629d0a1a2dc883e862dd27e6010ab6a9.
