### ISSUE TITLE
Update concentratord runtime stats_interval with the configured gateway stats_interval from a GatewayConfiguration ChirpStack message

### ISSUE THREAD

**Issue by nicolas-juteau** [chirpstack/chirpstack-concentratord#181]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-concentratord) of this repository and believe that this is not a duplicate.

## Summary

ChirpStack already relays the configured gateway stats_interval in a GatewayConfiguration message sent to concentratord. However, concentratord just seem to silently ignore the stats_interval and simply proceeds to channel reconfiguration, if required.

## What is the use-case?

- For gateways with cellular back-haul, having the possibility to remotely finetune the heartbeat message interval would be incredibly useful
- There are situations in which reducing the heartbeat message interval temporarily would be useful (gateway installation, gateway servicing) as the heartbeat message also exposes dynamic metadatas/commands outputs that can carry insight about the gateway operational status

## Implementation description

Looks like updating `config.concentratord.stats_interval` with the received `new_config.stats_interval` in function `update_configuration` of files src/handler/config.rs would do the trick.

I don't know why it is not already done in the first place.

## Can you implement this by yourself and make a pull request?
Yes. However, my rust knowledge is rusty (aka non-existent) and it would without a doubt be cleaner if done by knowledged rust developer

**Comment by brocaar** [comment]
Thanks for reporting, the above commit fixes this.
