### ISSUE TITLE
Incorrect gateway ID for MTCAP3 gateways

### ISSUE THREAD

**Issue by nicolas-juteau** [chirpstack/chirpstack-concentratord#186]
On chirpstack-mqtt-forwarder start, the gateway id is retrieved. However, for the Multitech MTCAP3 gateway, an incorrect gateway id is retrieved. The retrieved gateway ID should match the EUI of the installed LoRa card.

2024-10-22T15:46:59.485415+00:00 mtcap3 chirpstack-mqtt-forwarder[16915]: Reading gateway id
2024-10-22T15:46:59.493354+00:00 mtcap3 chirpstack-mqtt-forwarder[16915]: Received gateway id, gateway_id: 0016c0XXXXXXXXXX

root@mtcap3:/var/config/home/mtadm# mts-io-sysfs show lora/eui
00:80:00:XX:XX:XX:XX:XX

Specifying (or not) a gateway_id in the concentratord config does not change this behavior.

Using:
chirpstack-concentratord-sx1302 4.4.4
chirpstack-mqtt-forwarder 4.3.1
mLinux 6.3.0

**Comment by nicolas-juteau** [comment]
Done: https://github.com/chirpstack/chirpstack-concentratord/pull/187

**Comment by brocaar** [comment]
#187 has been merged, thanks for your work :+1:
