### ISSUE TITLE
support  build-mipsel-unknown-linux-musl

### ISSUE THREAD

**Issue by DanielCao0** [chirpstack/chirpstack-concentratord#197]
Can add a new target ? build-mipsel-unknown-linux-musl. Thank you.

**Comment by brocaar** [comment]
Hi @DanielCao0, do you mean just in the `Makefile`, or also distributing `.ipk` packages? I assume your request would be for the RAK target is that correct (like for the `chirpstack-mqtt-forwarder`)?

**Comment by DanielCao0** [comment]
> Hi @DanielCao0, do you mean just in the `Makefile`, or also distributing `.ipk` packages? I assume your request would be for the RAK target is that correct (like for the `chirpstack-mqtt-forwarder`)?

Yes, I mean just Makefile add mipsel (RAK)  target.   (like for the chirpstack-mqtt-forwarder and mesh)

**Comment by brocaar** [comment]
Hi @DanielCao0 please see the above commit.

**Comment by DanielCao0** [comment]
Thank you.
