### ISSUE TITLE
chirpstack-concentratord-sx1302 fails to start with RAK2287 USB GPS EU868

### ISSUE THREAD

**Issue by muhlpachr** [chirpstack/chirpstack-concentratord#23]
I am unable to start concentratord for RAK2287 USB GPS EU868 on RPi armv7hf

```
sudo ./chirpstack-concentratord-sx1302 -c concentratord.toml
...
WARNING: MCU version mismatch (expected:01.00.00, got:V00.02.06)
INFO: Concentrator MCU version is V00.02.06
INFO: MCU status: sys_time:40524090 temperature:-0.0oC
ERROR: received wrong ACK type (0xFF)
ERROR: failed to read REQ_MULTIPLE_SPI ack
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "lgw_start failed"', chirpstack-concentratord-sx1302/src/main.rs:111:15
```

Configuration used from https://www.chirpstack.io/concentratord/install/config/ for sx1302 with those modifications:
```
[gateway]
  antenna_gain=0
  lorawan_public=false
  model="rak_2287_eu868"
  model_flags=["GNSS","USB"]
  gateway_id="fc7c47f60740c21f"
```

sudo ./chirpstack-concentratord-sx1302 --version
chirpstack-concentratord-sx1302 3.2.0

Sources from release tag v3.3.0 (Latest)

**Comment by brocaar** [comment]
Sorry for the very late response. I missed this issue:

> WARNING: MCU version mismatch (expected:01.00.00, got:V00.02.06)

This explains the issue. You need to update your MCU firmware. See also:
https://github.com/Lora-net/sx1302_hal/tree/master/util_boot

Note that if you are using the latest ChirpStack Gateway OS, then you can perform this upgrade using the web-interface:

![image](https://github.com/chirpstack/chirpstack-concentratord/assets/165497/5993561d-8255-4970-a4e5-f377177cefbe)
