### ISSUE TITLE
add Semtech SX1302 CoreCell CN490 to chirpstack-concentratord

### ISSUE THREAD

**Issue by blockchain4trust** [chirpstack/chirpstack-concentratord#26]
[sx1302c490gw1_cn490.zip](https://github.com/brocaar/chirpstack-concentratord/files/8184321/sx1302c490gw1_cn490.zip)

China occupies more than 50% of the LoRa market, and more and more developers are making gateways based on sx1302. It is strange that there is no CN490 option in ChirpStack Concentratord.

For this, I have added the sx1302c490gw1_cn490.rs file（this attach file), hoping that the next version of ChirpStack Concentratord will add the CN490 band. Let more Chinese users use ChirpStack, enrich the community, and exert greater influence.

**Comment by jry485** [comment]
谢谢

> [sx1302c490gw1_cn490.zip](https://github.com/brocaar/chirpstack-concentratord/files/8184321/sx1302c490gw1_cn490.zip)
> 
> 中国占据了超过50%的LoRa市场，越来越多的开发者在做基于sx1302的网关。奇怪的是ChirpStack Concentratord里没有CN490这个选项。
> 
> 为此，我添加了sx1302c490gw1_cn490.rs文件（this attach file），希望下一个版本的ChirpStack Concentratord能加入CN490频段。让更多的中国用户使用ChirpStack，丰富社区，发挥更大的影响力。

谢谢共有！真在为没有CN490感觉困扰。谢谢！
