### ISSUE TITLE
Add support for the IMST iC280A

### ISSUE THREAD

**Issue by vanStadenRJ** [chirpstack/chirpstack-concentratord#28]
Currently the ChirpStack Concentratord only supports the Semtech 2.4 GHz reference design (SX1280) as option to setup the LoRa concentrator shield.  In addition to the already supported iC880A and iC980A, the newest IMST iC280A could be a nice addition to the supported concentrator modules.

**Comment by brocaar** [comment]
Thanks for letting me know about this module. However, I see that it is not yet on sale / available?
