### ISSUE TITLE
Request AS923 and US915 support for Seeed WM1302 module

### ISSUE THREAD

**Issue by hereismeaw** [chirpstack/chirpstack-concentratord#38]
Currently there are only EU868 preset for Seeed WM1302 on Concentratord. I Already tried to changed channel plan and test on Dragino LDDS75 sensors but doesn't work.

I'm using on SenseCAP M1, It would be nice for running dual mode Helium network and Chirpstack.

![photo_2023-01-18_23-08-25](https://user-images.githubusercontent.com/85986506/213244904-aed7bf11-26e6-4de2-a1e3-0f8bd36dc3cf.jpg)

![photo_2023-01-18_23-08-25 (2)](https://user-images.githubusercontent.com/85986506/213244953-8415b47e-1891-4f1e-8ae3-30bfe4d4f02d.jpg)

**Comment by brocaar** [comment]
Bot regions are now included for the WM1302 region support:
https://github.com/chirpstack/chirpstack-concentratord/blob/master/chirpstack-concentratord-sx1302/src/config/vendor/seeed/wm1302.rs
