### ISSUE TITLE
LoRa server with RAK5146 (using mini PCI to USB) and Raspberry Pi3

### ISSUE THREAD

**Issue by saroguti** [chirpstack/chirpstack-concentratord#43]
- [ X ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/brocaar/chirpstack-concentratord) of this repository and believe that this is not a duplicate.

## What happened?

chirpstack-concentrator not initialized

## What did you expect?

Create a local server to send and receive information to an end node.

## Steps to reproduce this issue

Steps:

1. installed ChirpStack Gateway OS full version
2. I used a RAK5146 hub with a mini PCI adapter and a Raspberry Pi3.

## Could you share your log output?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/113715504/216710640-4a9a2582-8baa-462b-8f46-3b6ac0ee4a31.png)

![Uploading MicrosoftTeams-image.png…]()

I've tried everything and it doesn't work at all :/

**Comment by brocaar** [comment]
Just to confirm, your RAK5146 is the USB model instead of the SPI model? In that case, you need to set the `USB` model flag. See this Concentratord section:

```toml
  # Gateway vendor / model flags.
  #
  # Flag can be used to configure additional vendor / model features. The
  # following flags can be used:
  #
  #   Global flags:
  #     GNSS - Enable GNSS / GPS support
  #     USB  - Use USB for concentrator communication (default is SPI)
  model_flags=[]
```

E.g. `model_flags=["USB"]`
