### ISSUE TITLE
Default metadata configurability

### ISSUE THREAD

**Issue by mullerch** [chirpstack/chirpstack-concentratord#64]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-concentratord) of this repository and believe that this is not a duplicate.

## Summary

Concentratord does add metadata to the stats report. The concentratord should provide a mecanism to disable those metadata.

## What is the use-case?

These metadata may not be needed and users may want to remove them to save bandwidth (e.g. mobile data plan).

## Implementation description

I suggest adding a `[metadata]` section to the configuration file with a `concentratord` property that would default to `concentrator_temp,concentratord_version,config_version,hal_version,model` (array of string of enabled metadata).

```
[metadata]

concentratord="concentrator_temp,concentratord_version,config_version,hal_version,model"
```

Redefining this property to empty would allow the user to remove those metadata. The default behavior is retro-compatible.

## Can you implement this by yourself and make a pull request?

Possibly.

## Workaround

I could not find a workaround to remove the metadata. Any idea is welcome.

**Comment by brocaar** [comment]
Have you evaluated what would be the saving in MBs on a monthly basis? In case of a cellular back-haul, I would first suggest the reduce the stats interval, e.g. from 30 seconds to 5 minutes.

Note that in case of ChirpStack, it would also cause the NS to malfunction as it needs the config version to validate that the Concentratord channel-plan is correctly configured. If not it will send a reconfiguration command (and it will keep sending this until the Concentratord is in sync).
