### ISSUE TITLE
Request AS923 channel-plan region for Shield Model  Seeed WM1302 / Seeed WM1303 

### ISSUE THREAD

**Issue by eddyantow** [chirpstack/chirpstack-concentratord#86]
We already installed v4.2.0-test.1 ChirpStack Gateway OS image on Raspberry Pi 4 with Seeed WM1303 LoRaWAN, 
but it seems AS923-2 channel plan region still not implemented by Concentratord for this shield.
It will be helpful if this channel plan region can be implemented, since our country, Indonesia use this 
channel plan.

![ChirpStack channel region](https://github.com/chirpstack/chirpstack-concentratord/assets/66015523/3fc1f792-f048-4212-a8e4-b4ac9a1cabc2)

**Comment by brocaar** [comment]
The above commit adds additional regions for the WM1302 module.
